##############################################################################
#
# GitGub CI workflow syntax spec:
#    https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
#
# CodeCov github action setup:
#    https://github.com/codecov/codecov-action
#
# CodeCov badge setup:
#    https://docs.codecov.com/docs/status-badges
#
# version 1.2
##############################################################################
name: Run Unit Test and Upload Coverage Report
on:
  # Triggered whenever push to main or impl-pid-controller
  push:
    branches: [ "main", "impl-pid-controller" ]
  # Triggered whenever a pull request is created on main
  pull_request:
    branches: [ "main" ]
    types: [opened, synchronize, reopened]
  # Allow manual trigger
  workflow_dispatch:
jobs:
  build-run-upload:
    # Create a container of the latest Ubuntu
    runs-on: ubuntu-24.04
    steps:
      # Checkout the repository
      - uses: actions/checkout@v4
      
      # Install build packages
      - name: Install build packages
        run: |
          sudo apt update
          sudo apt install -y software-properties-common
          sudo apt install -y doxygen lcov gcovr
      
      # Build, run unit test, and generate coverage report
      - name: Configure CMake flags and build executables
        run: |
          cmake -D WANT_COVERAGE=ON -D CMAKE_BUILD_TYPE=Debug -S ./ -B build/
          cmake --build build/ --clean-first --target all test_coverage
      
      # Display coverage info for debugging
      - name: Display coverage info
        run: |
          echo "Coverage report generated:"
          ls -lh build/test_coverage.info
          echo "First 50 lines of coverage:"
          head -n 50 build/test_coverage.info
      
      # Upload coverage result to CodeCov
      - name: Upload coverage result to CodeCov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./build/test_coverage.info
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
          verbose: true
          disable_search: true
